\name{NEWS}
\title{News for Package \pkg{oHMMed}}

\section{Changes in version 1.0.1}{
    \itemize{
    	    \item Fixed an issue in the graph generated by \code{conf_mat} specifically on Debian and Fedora systems. The graph was not rendering correctly.
    	}
}

\section{Changes in version 1.0.0}{
    \itemize{
    	    \item initial release
    	}
}

